### ISSUE TITLE
TF build error

### ISSUE THREAD

**Issue by klpanagi** [rapp-project/rapp-robot-nao#12]
Building ROS-TF using [vm_compile_additional_packages.sh](https://github.com/rapp-project/rapp-robot-nao/blob/master/scripts/vm_scripts/vm_compile_additional_packages.sh) fails.

The error was produced on a clean-vm, while following the documentation section: [Installation of necessary packages](https://github.com/rapp-project/rapp-robot-nao/wiki/Installation-of-necessary-packages)

Build Error:

```bash
Building CXX object CMakeFiles/pytf_py.dir/src/pytf.cpp.o
/home/nao/ws_ros_additional_packages/src/geometry/tf/src/tf.cpp:439:13: error: prototype for 'std::string tf::Transformer::allFramesAsDot(double) const' does not match any in class 'tf::Transformer'
/home/nao/ws_ros/install_isolated/include/tf/tf.h:297:15: error: candidate is: std::string tf::Transformer::allFramesAsDot() const
/home/nao/ws_ros_additional_packages/src/geometry/tf/src/pytf.cpp: In function 'PyObject* allFramesAsDot(PyObject*, PyObject*, PyObject*)':
/home/nao/ws_ros_additional_packages/src/geometry/tf/src/pytf.cpp:149:60: error: no matching function for call to 'tf::Transformer::allFramesAsDot(double)'
/home/nao/ws_ros/install_isolated/include/tf/tf.h:297:15: note: candidate is: std::string tf::Transformer::allFramesAsDot() const
make[2]: *** [CMakeFiles/tf.dir/src/tf.cpp.o] Error 1
make[1]: *** [CMakeFiles/tf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 45%] Building CXX object CMakeFiles/pytf_py.dir/src/tf.cpp.o
make[2]: *** [CMakeFiles/pytf_py.dir/src/pytf.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/nao/ws_ros_additional_packages/src/geometry/tf/src/tf.cpp:439:13: error: prototype for 'std::string tf::Transformer::allFramesAsDot(double) const' does not match any in class 'tf::Transformer'
/home/nao/ws_ros/install_isolated/include/tf/tf.h:297:15: error: candidate is: std::string tf::Transformer::allFramesAsDot() const
make[2]: *** [CMakeFiles/pytf_py.dir/src/tf.cpp.o] Error 1
make[1]: *** [CMakeFiles/pytf_py.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by klpanagi** [comment]
@maciek-slon, @dudekw  any updates/suggestions?...

We need a valid NAO-VM setup process in order to deploy and evaluate the **Object-Detection RApp**

**Comment by maciek-slon** [comment]
I'm waiting for response from @mfigat as he prepared VM for NAO.

**Comment by etsardou** [comment]
Is it possible to upload the VM somewhere (not publicly). just to both work at the same time?

**Comment by maciek-slon** [comment]
I will try to send you our working VM tomorrow morning.

2017-01-03 16:50 GMT+01:00 Manos Tsardoulias <notifications@github.com>:

**Comment by dudekw** [comment]
Sorry for the delay. It was an error caused probably by a change in ROS package repository. The new script should work fine. 

Now you should:
1)  clear the _~/ws_ros_additional_packages_ directory:
`rm -rf ~/ws_ros_additional_packages/*`
2) pull the rapp-robot-nao git repository:
`cd ~/ws_rapp_nao/src/rapp-robot-nao`
`git pull`
`cd ~`
3) run new script:
`vm_compile_additional_packages.sh`

Please contact me in case of any further problems.
