### ISSUE TITLE
vm_compile_rapp_core_agent fails

### ISSUE THREAD

**Issue by klpanagi** [rapp-project/rapp-robot-nao#14]
Compilation of **rapp_core_agent** using the **vm_compile_rapp_core_agent** script produces the following error (after success execution of vm_compile_additional_packages script):

```bash
CMake Error at /home/nao/ws_ros/install_isolated/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by "eigen_conversions"
  with any of the following names:

    eigen_conversionsConfig.cmake
    eigen_conversions-config.cmake

  Add the installation prefix of "eigen_conversions" to CMAKE_PREFIX_PATH or
  set "eigen_conversions_DIR" to a directory containing one of the above
  files.  If "eigen_conversions" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)


-- Configuring incomplete, errors occurred!
<== Failed to process package 'rapp_api_nao': 
  Command '/home/nao/ws_rapp_nao/install_isolated/env.sh cmake /home/nao/ws_rapp_nao/src/rapp-robot-nao/rapp_api_nao -DCATKIN_DEVEL_PREFIX=/home/nao/ws_rapp_nao/devel_isolated/rapp_api_nao -DCMAKE_INSTALL_PREFIX=/home/nao/ws_rapp_nao/install_isolated -DCMAKE_BUILD_TYPE=Release -DCMAKE_MODULE_PATH=/home/nao/ws_ros_additional_packages/programs/eigen-eigen-bdd17ee3b1b3/cmake' returned non-zero exit status 1

```

Any suggestions?

**Comment by dudekw** [comment]
I need some time to reproduce this error and prepare fix commands. If you are in hurry, you can try: 
1) check if the ws_ros workspace contains eigen_conversions pkg (part of the geometry pkg)
2) if you can't find it, you should install it in the ws_ros_additional_packages workspace. To do so, download it from the ROS repository: https://github.com/ros/geometry
 to src directory and compile workspace with vm_compile_additional_packages script.

I'll fix this error as soon as possible. Sorry for inconvenience.

**Comment by dudekw** [comment]
I need more time to rebuild all packages and perform proper check of the vm_compile_rapp_core_agent script

**Comment by klpanagi** [comment]
Thank you for the comments @dudekw.
I managed to  get passed that error, though i am currently facing a build error related to the rapp-api:

```bash
CMake Error at CMakeLists.txt:20 (find_package):
  By not providing "FindRapp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Rapp", but
  CMake did not find one.

  Could not find a package configuration file provided by "Rapp" with any of
  the following names:

    RappConfig.cmake
    rapp-config.cmake

  Add the installation prefix of "Rapp" to CMAKE_PREFIX_PATH or set
  "Rapp_DIR" to a directory containing one of the above files.  If "Rapp"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
<== Failed to process package 'rapp_api_nao': 
  Command '/home/nao/ws_rapp_nao/install_isolated/env.sh cmake /home/nao/ws_rapp_nao/src/rapp-robot-nao/rapp_api_nao -DCATKIN_DEVEL_PREFIX=/home/nao/ws_rapp_nao/devel_isolated/rapp_api_nao -DCMAKE_INSTALL_PREFIX=/home/nao/ws_rapp_nao/install_isolated -DCMAKE_BUILD_TYPE=Release -DCMAKE_MODULE_PATH=/home/nao/ws_ros_additional_packages/programs/eigen-eigen-bdd17ee3b1b3/cmake' returned non-zero exit status 1

```

**Comment by dudekw** [comment]
before you run the vm_compile_rapp_core_agent, you need to run the vm_compile_rapp_api script. Have you done it?

**Comment by dudekw** [comment]
We need to change the installation [wiki](https://github.com/rapp-project/rapp-robot-nao/wiki/Download-and-compilation-of-core-agent) @mfigat .

**Comment by dudekw** [comment]
You need to clone rapp-api repos to `~/ws_rapp_api/src`:
`WS_RAPP_API_DIR="/home/nao/ws_rapp_api"`
`mkdir -p $WS_RAPP_API_DIR/src`
`cd $WS_RAPP_API_DIR/src`
`git clone https://github.com/rapp-project/rapp-api.git`
`git clone https://github.com/rapp-project/rapp-robots-api.git`

**Comment by klpanagi** [comment]
@dudekw thank you for the feedback.
4a8a94eb273c4f0c555e41fb1ded00ff2c8d44b1 fixes the rapp-api and rap-core-agent compilation errors
