### ISSUE TITLE
Linking error against rapp-api and rapp-robots-api

### ISSUE THREAD

**Issue by klpanagi** [rapp-project/rapp-robot-nao#15]
I tried to build the [rapp_learn_object](https://github.com/maciek-slon/rapp_learn_object) application and i get link errors against the 2 rapp apis (robots, cloud).

Both the **RappConfig.cmake** and **RappRobotsConfig.cmake** are loaded properly by cmake, though i get the following error at link time:

```bash
Linking CXX executable LearnObject
/usr/bin/ld: cannot find -lrapp
/usr/bin/ld: cannot find -lrapp_robot_vision
/usr/bin/ld: cannot find -lrapp_robot_navigation
/usr/bin/ld: cannot find -lrapp_robot_communication
/usr/bin/ld: cannot find -lrapp_robot_info
/usr/bin/ld: cannot find -lrapp_robot_localization
collect2: error: ld returned 1 exit status
make[2]: *** [LearnObject] Error 1
make[1]: *** [CMakeFiles/LearnObject.dir/all] Error 2
make: *** [all] Error 2
```

Inlcude and library paths are set properly in both these .cmake files
```
/home/nao/ws_rapp_api/install/include
/home/nao/ws_rapp_api/install/lib
```

Of course, if i set the `LD_LIBRARY_PATH` env variable, those libraries are found properly, though there should not be a need to set that variable as the library paths should be set by cmake after loading RappConfig.cmake and RappRobotsConfig.cmake files.

Any ideas/suggestions?

**Comment by dudekw** [comment]
You need to use the `wut` branch of the _rapp-robots-api_ repository and there should not be any linking errors now.

**Comment by klpanagi** [comment]
Thank you @dudekw
